// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsvyzgectipezfozetnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdnl6Z2VjdGlwZXpmb3pldG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODQ2NjQsImV4cCI6MjA1OTY2MDY2NH0.dK4_5x6HNqFLTD60RwihykRQIu0yko5SDokxxe-GQJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);